### ISSUE TITLE
Susceptible to timing attacks

### ISSUE THREAD

**Issue by jceipek** [dwin/goArgonPass#1]
I ended up using "golang.org/x/crypto" directly in my own project, but just as a heads up, this implementation currently uses a time-insecure hash comparison because it early outs when it finds a mismatching byte here: https://github.com/dwin/goArgonPass/blob/master/password.go#L142

You can read about timing attacks here: https://codahale.com/a-lesson-in-timing-attacks/ but the core issue is that a determined attacker could measure the difference in execution time between a `comparisonHash` that has more vs fewer initial bytes in common with `decodedHash`.

Go's crypto library provides a time-secure comparison function you can use instead: https://golang.org/pkg/crypto/subtle/#ConstantTimeCompare

Full disclosure: I am not a cryptographer, nor do I know the specifics of how Argon2 works.

**Comment by dwin** [comment]
Thanks!
